[build]
    command = "hugo --gc --minify"
    publish = "public"
    
[context.production.environment]
    HUGO_VERSION = "0.81.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"


[context.deploy-preview]
    command = "hugo --gc --minify -D -F"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.81.0"